name: Upcoming Data Pull

on:
  schedule:
    - cron: '3 5,13,16 * * *' # Runs every day at 6:03 AM, 2:03 PM, and 5:03 PM (WAT)
  workflow_dispatch:

jobs:
  scrape_today_data:
    runs-on: ubuntu-latest
    env:
      TZ: Africa/Lagos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data scraping script
        id: run_etl
        run: |
          python today.py > output.txt
          echo "script_output<<EOF" >> $GITHUB_OUTPUT
          cat output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Send Slack notification
        
        if: success() 
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ vars.GENERAL_SLACK_CHANNEL_ID }}",
              "username": "aTom_yml",
              "icon_emoji": ":cloud:",
              "text": ":incoming_envelope: Upcoming - Run ${{ github.run_number }} :heavy_check_mark:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.run_etl.outputs.script_output }}"
                  }
                }
              ]
            }
