name: Pull live data to find promising teams matching the ht criteria

on:
  schedule:
    - cron: '0/5 7-23 * * *' # Runs every 5 minutes from 7 AM to 11 PM
  workflow_dispatch:

jobs:
  scrape_live_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run etl script
        run: |
          python etl_pipeline.py
      # - name: Upload scraped data artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: scraped-data
      
      - name: Send Slack notification
        
        if: success() 
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ vars.SLACK_CHANNEL_ID }}",
              "text": "Deploying to the production environment. Final preview - PR #${{ github.run_number }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Found promising events\n"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Title:*\n<insert here>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*place data here:*\n`${{ github.head_ref }}`"
                    }
                  ]
                }
              ]
            }


