name: Pull and save upcoming events for the day

on:
  schedule:
    - cron: '0 6 * * *' # Runs every day at 6 AM
  workflow_dispatch:

jobs:
  scrape_today_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data scraping script
        run: |
          python today.py
      # - name: Upload scraped data artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: scraped-data
      
      - name: Send Slack notification
        
        if: success() 
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ vars.SLACK_CHANNEL_ID }}",
              "text": "Upcoming data summary is ready - Run ${{ github.run_number }} :heavy_check_mark:",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Upcoming Data Summary is ready\n"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Number of Events for today:*\n`$(wc -l < today_events.csv)`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Number of Promising Events:*\n`$(wc -l < promising_events.csv)`"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Data"
                      },
                      "url": "https://github.com/atom/data/promising_events.csv"
                    }
                  ]
                }
              ]
            }


