name: Live Data Pull

on:
  schedule:
    - cron: '0/5 7-23 * * *' # Runs every 5 minutes from 7 AM to 11 PM
  workflow_dispatch:

jobs:
  scrape_live_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run etl script
        run: |
          python live.py > output.txt
          echo "script_output<<EOF" >> $GITHUB_OUTPUT
          cat output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Send Slack notification
        if: success() 
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ vars.LIVE_SLACK_CHANNEL_ID }}",
              "text": "Found promising event(s) - Run ${{ github.run_number }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Found promising event(s)\n"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Title:*\n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Script Output:*\n${{ steps.run_etl.outputs.script_output }}"
                    }
                  ]
                }
              ]
            }
