name: Live Data Pull

on:
  schedule:
    - cron: '0/6 6-22 * * *' # Runs every 6 minutes from 7 AM to 11 PM (WAT)
  workflow_dispatch:

jobs:
  scrape_live_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run etl script
        id: run_etl
        run: |
          python live.py > output.txt
          echo "script_output<<EOF" >> $GITHUB_OUTPUT
          cat output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          # Check if output contains 👀 emoji
          if grep -q "👀" output.txt; then
            echo "send_slack=true" >> $GITHUB_OUTPUT
          else
            echo "send_slack=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Send Slack notification
        if: success() && steps.run_etl.outputs.send_slack == 'true'
        uses: slackapi/slack-github-action@v2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ vars.LIVE_SLACK_CHANNEL_ID }}",
              "username": "aTom_yml",
              "icon_emoji": ":cloud:",
              "text": ":hourglass_flowing_sand: Live | Action Required - Run ${{ github.run_number }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ steps.run_etl.outputs.script_output }}"
                  }
                }
              ]
            }
